### ISSUE TITLE
Use as seeder without using the entity decorators

### ISSUE THREAD

**Issue by pxDot** [CyriacBr/mikro-resources#4]
I want to use a seeder with mikro-orm similar to typeorm-seeder. However, I don't want to pollute my entities with decorators as the seeding is only needed for e2e tests and I want to keep my entities and code base clean of code used for testing purposes.

I also need to be able to generate e.g. 10 Entities with specifically set fields from `faker` like `firstName` but without using said decorators in the entities. Is it possible to do e.g. `factory.make(Author).with({ firstName: faker.name.firstName() }).manyAndPersist(10);` or can the `with()` mehtod only be used for creating one author?

**Comment by CyriacBr** [comment]
I should have made it clear in the readme, but the `@Fixture` decorator is only needed for customization. It isn't needed for making the factory work as MikroORM already holds entities metadata.
And yes, `with().many()` works, I just added a test, thanks!
I think I'll actually allow `with` to take a callback so you can further customize entities when there are many of them.
```ts
factory.make(Author)
  .with(i => ({
    name: `Author #${i}`
  }))
  .many(10);
```

**Comment by pxDot** [comment]
Sounds great. Thanks for the insight. Was very helpful. Was one of the last things holding me back to migrate from TypeORM to MikroORM, but thanks to you I think I can finally make that switch now 🥇

**Comment by CyriacBr** [comment]
Do let me know if you bump into any issue with `mirko-resources`.
