### ISSUE TITLE
Use with CLI for CI/CD

### ISSUE THREAD

**Issue by pxDot** [CyriacBr/mikro-resources#6]
Hi,

as I am further planning on migrating my projects from TypeORM to MikroORM I noticed another issue I am having right now with seeding:

Before I was using typeorm-seeding (https://github.com/w3tecch/typeorm-seeding) which has a build in CLI to start seeding the DB, which is great for usage in CI/CD pipelines to set up a test database for e2e tests.

Is this somehow possible with this package? I want to keep migrations, seeds and tests seperated as much as possible from the main code.

**Comment by CyriacBr** [comment]
There is no CLI but nothing stops you from running `ts-node my_seed_script.ts` where you create a MikroORM connection and run the factories there.
```ts
const orm = await MikroORM.init(ormConfig);
const factory = new FixtureFactory(orm, { logging: true });

await factory.make(Author).oneAndPersist();
```

**Comment by pxDot** [comment]
This should work too. Thank you.

**Comment by CyriacBr** [comment]
Btw for Mikro ORM v4 you need to install the `next` version of mikro-resources. I haven't tested with the latest v4 release tho. I will as soon as I can.
